filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.logstash:
  hosts: ["elk:5044"]
  ssl:
      certificate_authorities:
      - /etc/pki/tls/certs/logstash-beats.crt
