version: '3.8'

networks:
  database-network:
    name: database-network
    #driver: bridge

volumes:
  database_device:
    driver: local
    name: database_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/transcendence/volumes/E

services:

  database:
    image: postgres:16.0-alpine3.18
    container_name: transc-db
    hostname: ${POSTGRES_DB}
    networks:
      - database-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - database_device:/var/lib/postgresql/data
      - ./database/init-scripts/:/docker-entrypoint-initdb.d/
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
    #FIXME: for development to allow editing the code outside the container
    volumes:
      - ./backend/transc:/app/transc
    depends_on:
      - database
    networks:
      - database-network

  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
    depends_on:
      - backend
    ports:
     - "80:80"
