version: '3.8'

networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge

volumes:
  frontend:
    driver: local
    name: frontend
    driver_opts:
      type: none
      o: bind
      device: /home/jj/data/transcendence/volumes/C

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3000:3000"
  
  #frontend:
   # build: 
    #  context: ./frontend
    #ports:
     # - "8080:8080"

  database:
    image: postgres:latest
    environment: 
      POSTGRES_PASSWORD: example
