version: '3.8'

networks:
  database-network:
    name: database-network
    driver: bridge
  transcendence-network:
    name: transcendence-network
    driver: bridge


volumes:
  database_device:
    driver: local
    name: database_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/transcendence/volumes/E
  backend_device:
    driver: local
    name: backend_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/transcendence/volumes/C
  #frontend_device:
  #  driver: local
  #  name: frontend_device
  #  driver_opts:
  #    type: none
  #    o: bind
  #    device: /home/jj/data/transcendence/volumes/D

services:
  database:
    image: postgres:10.4
    networks:
      - database-network
    ports:
      - '4000:4000'
    env_file:
      ./database/.env
    volumes:
      - $HOME/data/transcendence/volumes/E:/var/lib/postgresql/data
      - ./database/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    restart: always
    container_name: database
    hostname: database
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend/
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - transcendence-network
      - database-network
    volumes:
      - $HOME/data/transcendence/volumes/C:/var/lib/backend/data

  #frontend:
   # build: 
    #  context: ./frontend
    #ports:
     # - "8080:8080"

