version: '3.8'

networks:
  transcendence-network:
    name: transcendence-network
    driver: bridge

volumes:
  backend_device:
    driver: local
    name: backend_device
    driver_opts:
      type: none
      o: bind
      device: /home/jj/data/transcendence/volumes/C
  frontend_device:
    driver: local
    name: frontend_device
    driver_opts:
      type: none
      o: bind
      device: /home/jj/data/transcendence/volumes/D
  database_device:
    driver: local
    name: database_device
    driver_opts:
      type: none
      o: bind
      device: /home/jj/data/transcendence/volumes/E

services:
  backend:
    container_name: backend
    image: backend
    build: 
      context: ./backend/
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - transcendence-network
    volumes:
      - backend_device:/var/lib/C 

  #frontend:
   # build: 
    #  context: ./frontend
    #ports:
     # - "8080:8080"

  database:
    image: postgres
    build:                                            <-------  #TODOOOO create Dockerfile for database
      context: ./database/                            <-------  #TODOO create DOckerfile at this place
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - database_device:/var/lib/postgresql/data
    networks:
      - transcendence-network