version: "3.8"

include:
  - elastic-stack/docker-compose.yml

networks:
  database-network:
    name: database-network
    #driver: bridge

  redis-network:
    name: redis-network

  proxy-network:
    name: proxy-network

  elastic:
    external: true

volumes:
  database_device:
    driver: local
    name: database_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/transcendence/volumes/E # FIXME: Why mount here?

  backend_device:
    driver: local
    name: backend_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker-data/transcendence/backend

  redis_device:
    driver: local
    name: redis_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker-data/transcendence/redis

  nginx_logs:
    driver: local

  redis_logs:
    driver: local

  postgres_logs:
    driver: local

services:
  database:
    image: database
    build:
      context: ./database/
    labels:
      co.elastic.logs/module: postgresql
    container_name: transc-db
    hostname: ${POSTGRES_DB}
    networks:
      - database-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - database_device:/var/lib/postgresql/data
      - ./database/init-scripts/:/docker-entrypoint-initdb.d/
      - postgres_logs:/mnt/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U '${POSTGRES_USER}' -d '${POSTGRES_DB}'"]
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_MEDIA_URL: ${DJANGO_MEDIA_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_HOST: ${REDIS_HOST}
      DEFAULT_AVATAR_NAME: ${DEFAULT_AVATAR_NAME}

    volumes:
      - backend_device:/data/
      - ./backend/transc:/app/transc # FIXME: for development to allow editing the code outside the container
    depends_on:
      database:
        condition: service_healthy
    networks:
      - database-network
      - redis-network
      - proxy-network
    restart: unless-stopped

  redis:
    image: redis
    build:
      context: ./redis/
    labels:
      co.elastic.logs/module: redis
    container_name: ${REDIS_HOST}
    networks:
      - redis-network
    volumes:
      - redis_device:/var/lib/redis
      - redis_logs:/mnt/redis
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: "Dockerfile.${FRONTEND_ENV:-dev}"
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/app/src/:ro
      - ./frontend/public/:/app/public/:ro
      - ./frontend/index.html:/app/index.html:ro
    networks:
      - proxy-network
    restart: unless-stopped

  proxy:
    container_name: proxy
    labels:
      co.elastic.logs/module: nginx
    image: proxy
    build:
      context: ./proxy
    depends_on:
      - backend
      - frontend
    ports:
      - "443:443"
      - "5601:5601"
    networks:
      - proxy-network
      - elastic
    volumes:
      - ./.ssl/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro
      - ./.ssl/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key:ro
      - nginx_logs:/mnt/nginx
    restart: unless-stopped