version: '3.8'

networks:
  database-network:
    name: database-network
    driver: bridge
  transcendence-network:
    name: transcendence-network
    driver: bridge

volumes:
  database_device:
    driver: local
    name: database_device
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/transcendence/volumes/E
  backend_device:
    driver: local
    name: backend_device
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/transcendence/volumes/C
  frontend_device:
    driver: local
    name: frontend_device
    driver_opts:
      type: none
      o: bind
      device: /home/jj/data/transcendence/volumes/D

services:
  database:
    image: postgres
    container_name: ${POSTGRES_DB}
    hostname: ${POSTGRES_DB}
    networks:
      - database-network
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - /home/$USER/data/transcendence/volumes/E:/var/lib/postgresql/data
    restart: always
  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend/
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DATABSE_URL: ${POSTGRES_URL}
    depends_on:
      - database
    networks:
      - transcendence-network
      - database-network
    volumes:
      - /home/$USER/data/transcendence/volumes/C:/var/lib/backend/data
  frontend:
    container_name: frontend
    image: frontend
    build: 
      context: ./frontend
    depends_on:
      - backend
      - database
    volumes:
      - /home/$USER/data/transcendence/volumes/D:/var/lib/frontend/data
    ports:
     - "80:80"

