version: '3'

networks:
  database-network:
    name: database-network
    #driver: bridge

  redis-network:
    name: redis-network
  proxy-network:
    name: proxy-network

volumes:
  database_device:
    driver: local
    name: database_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/transcendence/volumes/E # TODO: Why mount here?

  redis_device:
    driver: local
    name: redis_device
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker-data/transcendence/redis

services:
  database:
    image: postgres:16.0-alpine3.18
    container_name: transc-db
    hostname: ${POSTGRES_DB}
    networks:
      - database-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_URL: ${POSTGRES_URL}
    volumes:
      - database_device:/var/lib/postgresql/data
      - ./database/init-scripts/:/docker-entrypoint-initdb.d/
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U '${POSTGRES_USER}' -d '${POSTGRES_DB}'"
        ]
      interval: 10s
      timeout: 30s
      retries: 30

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend/
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_URL: ${POSTGRES_URL}
      REDIS_HOST: ${REDIS_HOST}

    #FIXME: for development to allow editing the code outside the container
    volumes:
      - ./backend/transc:/app/transc
    depends_on:
      database:
        condition: service_healthy
    networks:
      - database-network
      - redis-network
      - proxy-network

  redis:
    image: redis:latest
    container_name: ${REDIS_HOST}
    restart: always
    networks:
      - redis-network
    volumes:
      - redis_device:/var/lib/redis

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/app/src/:ro
      - ./frontend/public/:/app/public/:ro
    networks:
      - proxy-network 
  proxy:
    container_name: proxy
    image: proxy
    build:
      context: ./proxy
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - proxy-network 
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
          
