filebeat.inputs:
- type: filestream
  id: default-filestream
  paths:
    - ingest_data/*.log

filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/mnt/nginx/access.log"]
  error:
    enabled: true
    var.paths: ["/mnt/nginx/error.log"]

- module: redis
  log:
    enabled: true
    var.paths: ["/mnt/redis/redis.log"]
  slowlog:
    enabled: true
    var.hosts: ["redis:6379"]

- module: postgresql
  log:
    enabled: true
    var.paths: ["/mnt/postgres/*.log"]

processors:
- add_docker_metadata: ~

setup:
  dashboards.enabled: true
  kibana:
    host: ${KIBANA_HOSTS}
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"
